<a href="https://colab.research.google.com/github/yash-hash/basics-/blob/master/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
#assesment 1
r=np.random.randint(50,100,10)
r.sort() #by default sorts the array in ascending order
reverse_order=np.sort(r)[::-1] #reverses the list  
reverse_order #printing the reversed list i.e. ascending order

array([96, 93, 87, 82, 77, 77, 67, 67, 60, 59])

In [0]:
#assesment 2
newr=np.append(r,7)
newr

array([59, 60, 67, 67, 77, 77, 82, 87, 93, 96,  7])

In [0]:
#assesment 3
sq = np.sqrt(r)
print(sq)
c = np.power(r,3)
print(c)


[7.07106781 7.48331477 8.48528137 8.77496439 8.77496439 9.05538514
 9.16515139 9.64365076 9.74679434 9.8488578 ]
[125000 175616 373248 456533 456533 551368 592704 804357 857375 912673]


In [0]:
#Asessment 4
Med = np.median(r)
print("Median is ",Med)
mean = np.mean(r)
print("Mean is ",mean)
print("max value",max(r))
print("min value",min(r))
print("Total sum",sum(r))

Median is  79.5
Mean is  78.3
max value 97
min value 50
Total sum 783


In [0]:
#Assesment 5
# nnormalizing an array
xmax=np.max(r)
xmin=np.min(r)
den=xmax-xmin
xnorm=(r-xmin)/den
print(xnorm)
print(r)

[0.         0.12765957 0.46808511 0.57446809 0.57446809 0.68085106
 0.72340426 0.91489362 0.95744681 1.        ]
[50 56 72 77 77 82 84 93 95 97]
